name: Tv


on:
 push:
    branches:
      - main
    tags:
      - 'init'
  # schedule:
  #   - cron: '*/10 * * * *' # Run every 10 minutes

jobs:
  tv:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20.12.2'

    - name: Install dependencies
      run: npm install

    - name: Run script
      run: npm run start
